<?php

/*
 * Implementation of hook_menu()
 */
function civiaccountsync_dummy_menu() {
    
    $items['admin/cas/plugins/civiaccountsync-dummy'] = array(
        'title'            => t('CiviAccountSync Dummy Settings'),
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('civiaccountsync_dummy_settings_form'),
        'access arguments' => array('administer civiaccountsync'),
        'type'             =>  MENU_NORMAL_ITEM,
        'weight'           => 3,
    );
    return $items;

}

function civiaccountsync_dummy_settings_form() {
    $form['nothing'] = array(
        '#markup' => '<center>' . t('There is nothing to see here') . '</center>'
    );
    return $form;
}